import fs from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";

const SKILL = fileURLToPath(new URL("../SKILL.md", import.meta.url));

/** This skill's SKILL.md. The skill is born from init: SKILL.md is generated from here, never edited by hand. */
export const SKILL_MD = `---
name: testing
description: Collect Suites of executable Cases into a Plan and run the Plan against a candidate to establish whether the protection it states holds.
---

# Testing

Testing establishes whether stated protection holds for a candidate. It knows three things, from the outside in, and leaves a fourth, Strategy, to the using system:

A **Plan** states a testing purpose and collects the Suites that serve it. It is Markdown: YAML frontmatter, then a body. The body, which must not be empty, states what the Plan protects and why, for the people and agents who author and review it. The frontmatter's \`suites\` lists the Suites it collects, each a relative posix path to a Suite directory beneath the testing root, each at most once. A Plan may collect no Suite yet. Testing owns only \`suites\` and the body: every other frontmatter key belongs to the using system, and Testing never reads it. Where a Plan lives, and who adds to it, is the using system's decision.

A **Suite** is a directory holding \`suite.json\`, whose one field, \`concern\`, states the coherent testing concern its Cases serve. The concern, not the current Cases, gives a Suite its meaning. Every Case file anywhere beneath the directory belongs to the Suite; there is no other membership. A Suite with no Case is refused, since it protects nothing.

A **Case** is one file named \`*.test.js\` or \`*.test.ts\`, or a module variant of either (\`.mjs\`, \`.cjs\`, \`.mts\`, \`.cts\`), whose tests use Node's test runner, \`node:test\`. Its tests state the claims it makes. A Case passes only when executing it succeeds and every test it reports ran and passed: a Case that ran no test, or skipped one, proves nothing.

A Case file is also a **Carrier** of traceable **Test Cases**. A Test Case opts into traceability by one explicit source declaration: a top-level statement of the Carrier that calls the local name of its value default import of \`node:test\` with exactly three arguments, none spread, a non-empty string literal name, an object literal holding a plain \`tests\` property, and anything as the third: \`import test from "node:test"; test("works offline", { tests: { requirement: ["works-offline"] } }, () => {});\`. Its identity is the Carrier's path and that name, written as the one-line JSON array of the two. \`tests\` is a literal object of kinds, each key a plain name and each value a non-empty list of distinct string-literal ids without whitespace; a Test Case may declare any number of references, and any number of Test Cases may declare the same one. It is refused when it is not that literal, when \`tests\` is stated twice in one options object, or when two declarations claim one name, since the identity is then ambiguous. The declaration is read from the Carrier's syntax, parsed with \`@babel/parser\`, never by executing it: text in strings and comments is nothing. It states trace meaning: this Test Case tests these things. It does not state that Node registered or ran the call, which a Run shows. Everything else, every other use of \`node:test\` and every other call or property, is ordinary syntax outside this capability: neither read nor refused. The reference belongs to the Test Case alone: what it names is never changed to learn of it and names no Test Case, a Suite or a Plan states none, and there is no index to keep. Testing knows no kinds and does not check that an id names anything; the using system decides which kinds it accepts and whether the meaning exists. A Test Case tests only what it names: no relation of the named meaning, such as one that replaces it, is followed. \`readTestCases\` and \`parseTestCases\` in \`scripts/test-cases.ts\` read the Test Cases of a Carrier, and \`testCasesTesting\` computes, from the Test Cases given, which of them test a kind and id. For TypeScript, \`scripts/tests-option.d.ts\` declares \`tests\` as an option of \`node:test\`: it is this skill's metadata, not something Node defines. Traceability is of the Test Case, while a Suite still collects Carriers and a Run still executes and reports them, a Case above being the Carrier.

A Test Case can supersede an earlier one, so its HOW moves on while the earlier one stays exactly as it was written. A Test Case may add one plain \`supersedes\` property beside \`tests\` in the same options object, a literal list of exactly two string literals, the carrier and the name that identify the earlier Test Case: \`test("how now", { tests: { requirement: ["works-offline"] }, supersedes: ["old.test.ts", "how then"] }, () => {});\`. It is refused when it is not that literal or is stated twice. The relation belongs to the newer Test Case alone, like a reference to meaning: the earlier one names nothing and is never touched, and the relation is computed from the Test Cases, never stored. Supersession records HOW history. It does not delete, invalidate or unrun the earlier Test Case, which stays addressable and runnable historical HOW, and it does not by itself make it inactive: whether a Test Case still protects something is decided per \`tests\` edge. A Test Case is active for a kind and id it tests unless a later Test Case of its own lineage, the line of Test Cases that supersede it one after another, tests that same kind and id too. So when TC₁ tests R1 and R2 and TC₂ supersedes TC₁ and tests R1, TC₂ is active for R1 and TC₁ remains active for R2, the only protection it has; a superseding Test Case need not test everything its predecessor tested. Activity is computed from the supersession graph and the \`tests\` edges of the Test Cases being considered, never from a stored flag, dates, history, ordering or where a Test Case lives, so the same Test Case can be active in some material and not in other. Testing refuses a lineage whose target names no Test Case among those it is given, that supersedes itself or is a circle, or that has a Test Case immediately superseded by more than one, since which is later would be ambiguous: it reads declared meaning only and never judges whether two Test Cases prove the same thing. \`readSupersession\` in \`scripts/supersession.ts\` returns each superseded Test Case's superseder with those errors, and \`currentTestCasesTesting\` the Test Cases, among those given, that are active for a kind and id. Supersession is of Test Cases, while a Suite still collects Carriers and a Run still executes them all: a Carrier may hold Test Cases beyond the ones it declares, so a superseded Test Case does not make its Carrier obsolete, and which Carriers carry the active Test Cases is not decided here.

A **Strategy** is the using system's lasting decisions about how it uses Testing: where Suites and Plans live and who owns them, which Plan is run, where and when, and how one Plan follows another. Testing reads no Strategy and interprets none of it; it executes only the Plan it is given.

Run a Plan with \`scripts/run.ts <plan> [candidate]\`. The testing root, which the Plan and its Suites are read from, is the current directory; the candidate, the state being tested, defaults to it. These are often the same state, but they are two roles: each Case is executed in its own process, with the candidate as its working directory, under the same Node and loaders (\`--import\`, \`--require\`, \`--loader\`) \`run.ts\` runs under, whether given on its command line or in \`NODE_OPTIONS\`, and none of its other options (with \`tsx\`, TypeScript Cases run as they are). A loader named by a relative path is resolved from where \`run.ts\` runs, so it names the same file in the candidate. Node's test runner reports each Case to a file of its own, apart from anything the Case prints, so only that report decides the Case. A Case reaches what it tests through its working directory, never through its own location, so the same Case can judge a candidate it was not written beside. Nothing checks that it does.

A broken Plan or Suite is refused before any Case runs. Otherwise the Run is printed: the Plan, the candidate, the conditions (Node version, platform, architecture), one \`pass\` or \`fail\` line per Case with the output of every Case that did not pass, and finally \`holds\` or \`does not hold\`. The Plan holds only if every Case of every Suite it collects passed; \`run.ts\` fails otherwise. From code, \`runPlan\` in \`scripts/testing.ts\` returns the Run, and \`readPlan\`, \`readSuite\` and \`readPlanSuites\` return the same errors.

Testing keeps no record of a Run: the Run is observed where it is executed. It does not bound a stuck Case, isolate a Case from the machine it runs on, or prove that the Plan, Suites and Cases it reads are the ones that were accepted; those belong to the using system. A Plan only collects: it cannot remove, replace or relate one Case to another, and Testing never judges whether two Cases prove the same thing.
`;

/** Generates this skill's SKILL.md at \`target\` (by default, next to this skill's scripts). */
export function init(target = SKILL): string {
  fs.writeFileSync(target, SKILL_MD);
  return target;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) init();
